apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: nginx-vpa-off
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deploy
  # updatePolicy:
  #   updateMode: "Off"           # observe only — Updater never evicts, Admission never patches
  updatePolicy: # Add to 02-vpa-off.yaml or create separately — change updateMode only
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
      - containerName: nginx
        minAllowed:
          cpu: 50m
          memory: 64Mi
        maxAllowed:
          cpu: 2
          memory: 2Gi
