apiVersion: v1
kind: Service
metadata:
  name: backend-sticky
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 80
