apiVersion: v1
kind: Service
metadata:
  name: fake-headless
spec:
  type: ClusterIP
  clusterIP: ""       # empty string — NOT the same as None
  selector:
    app: backend
  ports:
    - port: 5678
      targetPort: 5678
