apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      version: blue
  template:
    metadata:
      labels:
        app: nginx
        version: blue      # Blue label
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args:
          - "-text=BLUE VERSION - v1.0"
          - "-listen=:5678"
        ports:
        - containerPort: 5678
