apiVersion: apps/v1
kind: Deployment
metadata:
  name: immutable-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immutable-demo
  template:
    metadata:
      labels:
        app: immutable-demo
    spec:
      containers:
        - name: nginx
          image: nginx:1.30.4
