apiVersion: v1
kind: Service
metadata:
  name: confused-externalname
spec:
  type: ExternalName
  externalName: httpbin.org
  selector:
    app: backend    # this field is meaningless here — see below
  ports:
    - port: 5678
