apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: redis-trigger-auth
  namespace: keda-demo
spec:
  secretTargetRef:
    - parameter: password
      name: redis-queue
      key: redis-password
