apiVersion: v1
kind: Service
metadata:
  name: backend-svc-swapped
spec:
  type: ClusterIP
  selector:
    app: breakfix-backend2
  ports:
    - port: 5678 # swapped — this should be targetPort's value
      targetPort: 9090 # swapped — backend doesn't listen here
